### ISSUE TITLE
Comments on the notebook/documentation

### ISSUE THREAD

**Issue by hanxuh-hub** [lphansen/ClimateUncertaintySpillover#4]
1. Index page:
- Insert link to the draft.
- Insert link to rfs repo.
- Also insert section 1 (the introduction section) ?

2. Section 2:
- Insert figure 1 of the draft. 
- The histogram above section 2.2. does not look the same as figure 2 of the draft. Please use the same bins and range.
- There are some latex and citation issues in Remark 1 and 2. For example,  :raw-latex:`\cite{Joosetal:2013}` and :raw-latex:`\cite{Pierrehumbert:2014}`. Please address these issues.

3. Section 3:
- latex issue :  $ Y < {:raw-latex:`\tilde `y} :raw-latex:`le {overline y}`$

4. Section 4:
- The links to sections 2 and 3 (on the left panel) disappear when I enter section 4. Do you know what happens?

5. Section 5:
- Section 5.1, 5.2 and 5.3 repeat the contents in section 4, 2 and 3 respectively. I don't think we should keep these subsections.

6. Section 6:
- The last plot. The title does not appear until you move the slider. I believe you can make it visible before the slider is moved.

7. Section 7:
- There is a typo in the first line: This notebook presents computations in section 7 of **the** paper.
- For the plots with sliders, it seems "button" is a more natural choice? See this: https://plotly.com/python/custom-buttons/

**Comment by SuriChen1028** [comment]
Close this issue
